# Written by wing. It records which template generated this project and what each
# file looked like at the time, so `wing template update` can tell a file you edited
# from one the template changed. Commit it.

template = "rust"
name = "rune"
generated_at = "2026-09-01T15:01:04Z"

[[files]]
path = ".env.lua"
hash = "539a785c2afc77c1aedcf330c04a45b9"

[[files]]
path = ".github/workflows/release.yml"
hash = "8d55c45a115abffcfbd7ce9fa1d47f84"

[[files]]
path = ".github/workflows/tests.yml"
hash = "927278f544005e809480b4ef63410301"

[[files]]
path = ".gitignore"
hash = "48acb2973868b15571477eddfb6792e8"

[[files]]
path = ".make.lua"
hash = "bb7c5a8dcad3217c17d01346094d2d96"

[[files]]
path = "Cargo.toml"
hash = "7ad4921e5198b9b0b63b6ebf259526d6"

[[files]]
path = "PROJECT"
hash = "70ff68431490cd21887eafa79f09f8ca"

[[files]]
path = "README.md"
hash = "2883569824cac43273844352aabf82ae"

[[files]]
path = "examples/main.rs"
hash = "5d1446068109a320c965124c42430412"

[[files]]
path = "flake.nix"
hash = "0bb2daf842e7a19afbac05e8060b5d4a"

[[files]]
path = "src/lib.rs"
hash = "c4d1de7798ab458b5ad7ff3a52db8610"

